export type List = {
    id: string;
    name: string;
    context: string;
    createdAt: string;
    updatedAt: string;
    synced: boolean; // sync status
    deleted: boolean; // soft delete
}

export const fakeLists: List[] = [
    {
        id: '1',
        name: 'Work',
        context: 'Office',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '2',
        name: 'Personal',
        context: 'Home',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '3',
        name: 'Shopping',
        context: 'Grocery Store',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '4',
        name: 'Fitness',
        context: 'Gym',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '5',
        name: 'Travel',
        context: 'Vacation',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '6',
        name: 'Study',
        context: 'Library',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '7',
        name: 'Chores',
        context: 'Home',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '8',
        name: 'Projects',
        context: 'Work',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '9',
        name: 'Events',
        context: 'Social',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
    {
        id: '10',
        name: 'Miscellaneous',
        context: 'Various',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        synced: false,
        deleted: false,
    },
];

export const fakeTasks = [
    {
        id: '1',
        title: 'Task 1',
        description: 'Description for Task 1',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '1',
        createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        title: 'Task 2',
        description: 'Description for Task 2',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '1',
        createdAt: new Date().toISOString(),
    },
    {
        id: '3',
        title: 'Task 3',
        description: 'Description for Task 3',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '2',
        createdAt: new Date().toISOString(),
    },
    {
        id: '4',
        title: 'Task 4',
        description: 'Description for Task 4',
        completed: true,
        dueDate: new Date().toISOString(),
        late: true,
        list: '4',
        createdAt: new Date().toISOString(),
    },
    {
        id: '5',
        title: 'Task 5',
        description: 'Description for Task 5',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '4',
        createdAt: new Date().toISOString(),
    },
    {
        id: '6',
        title: 'Task 6',
        description: 'Description for Task 6',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '5',
        createdAt: new Date().toISOString(),
    },
    {
        id: '7',
        title: 'Task 7',
        description: 'Description for Task 7',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '6',
        createdAt: new Date().toISOString(),
    },
    {
        id: '8',
        title: 'Task 8',
        description: 'Description for Task 8',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '6',
        createdAt: new Date().toISOString(),
    },
    {
        id: '9',
        title: 'Task 9',
        description: 'Description for Task 9',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '7',
        createdAt: new Date().toISOString(),
    },
    {
        id: '10',
        title: 'Task 10',
        description: 'Description for Task 10',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '8',
        createdAt: new Date().toISOString(),
    },
    {
        id: '11',
        title: 'Task 11',
        description: 'Description for Task 11',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '8',
        createdAt: new Date().toISOString(),
    },
    {
        id: '12',
        title: 'Task 12',
        description: 'Description for Task 12',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '9',
        createdAt: new Date().toISOString(),
    },
    {
        id: '13',
        title: 'Task 13',
        description: 'Description for Task 13',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '14',
        title: 'Task 14',
        description: 'Description for Task 14',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '15',
        title: 'Task 15',
        description: 'Description for Task 15',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '16',
        title: 'Task 16',
        description: 'Description for Task 16',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '17',
        title: 'Task 17',
        description: 'Description for Task 17',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '18',
        title: 'Task 18',
        description: 'Description for Task 18',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '19',
        title: 'Task 19',
        description: 'Description for Task 19',
        completed: false,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
    {
        id: '20',
        title: 'Task 20',
        description: 'Description for Task 20',
        completed: true,
        dueDate: new Date().toISOString(),
        late: false,
        list: '10',
        createdAt: new Date().toISOString(),
    },
];